# Generated by Django 4.2.7 on 2023-11-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionAprendices', '0004_alter_aprendiz_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('tipo_visita', models.CharField(choices=[('presencia', 'Visita Presencial'), ('virtual', 'Visita Virtual')], max_length=10)),
                ('lugar', models.CharField(max_length=255)),
                ('numero_visita', models.IntegerField(choices=[(1, 'Visita 1'), (2, 'Visita 2'), (3, 'Visita 3')])),
                ('estado', models.CharField(choices=[('realizada', 'Realizada'), ('pendiente', 'Pendiente')], max_length=20)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAprendices.aprendiz')),
                ('instructor_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAprendices.instructorencargado')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
