# Generated by Django 4.2.7 on 2023-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendarcitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo_visita',
            field=models.CharField(choices=[('presencial', 'Visita Presencial'), ('virtual', 'Visita Virtual')], max_length=10),
        ),
    ]
