# Generated by Django 4.2.7 on 2023-11-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendarcitas', '0002_alter_visita_estado_alter_visita_tipo_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
