# Generated by Django 4.2.7 on 2023-11-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendarcitas', '0003_visita_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
