# Generated by Django 4.2.7 on 2024-05-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionAprendices', '0011_alter_formulariofinalaprendiz_practica_aprendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_evidencia_aprendizaje', models.BooleanField(blank=True, null=True)),
                ('fecha_recoleccion_evidencia', models.DateField(blank=True, null=True)),
                ('lugar_recoleccion_evidencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorActitudinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('satisfactorio', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactorTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('satisfactorio', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_informe', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_evaluado_inicio', models.DateField(blank=True, null=True)),
                ('periodo_evaluado_final', models.DateField(blank=True, null=True)),
                ('observaciones_ente_conformador', models.TextField(blank=True, max_length=250, null=True)),
                ('observaciones_aprendiz', models.TextField(blank=True, max_length=250, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='gestionAprendices.aprendiz')),
                ('factores_actitudinales', models.ManyToManyField(related_name='seguimientos', to='formatos.factoractitudinal')),
                ('factores_tecnicos', models.ManyToManyField(related_name='seguimientos', to='formatos.factortecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre_enteconformador', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_enteconformador', models.TextField(blank=True, null=True)),
                ('firma_aprendiz', models.TextField(blank=True, null=True)),
                ('nombre_instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_instructor', models.TextField(blank=True, null=True)),
                ('actividades', models.ManyToManyField(related_name='actividades', to='formatos.actividades')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='gestionAprendices.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoPlaneacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos_planeacion', to='gestionAprendices.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juicio_evaluacion', models.CharField(blank=True, max_length=100, null=True)),
                ('reconocimientos_especiales', models.BooleanField(blank=True, null=True)),
                ('reconocimientos_detalle', models.TextField(blank=True, null=True)),
                ('nombre_enteconformador', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_enteconformador', models.TextField(blank=True, null=True)),
                ('firma_aprendiz', models.TextField(blank=True, null=True)),
                ('nombre_instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_instructor', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestionAprendices.aprendiz')),
            ],
        ),
    ]
