# Generated by Django 4.2.7 on 2024-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='lugar_recoleccion_evidencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='nombre_actividad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='tiene_evidencia_aprendizaje',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='firma_aprendiz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='firma_enteconformador',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='firma_instructor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='juicio_evaluacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='reconocimientos_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='reconocimientos_especiales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formatoplaneacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formatoplaneacion',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='firma_instructor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones_ente_conformador',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='periodo_evaluado_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='periodo_evaluado_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
