# Generated by Django 4.2.7 on 2024-03-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_alter_actividades_lugar_recoleccion_evidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='firma_aprendiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='firma_enteconformador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='firma_instructor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nombre_enteconformador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='firma_aprendiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='firma_enteconformador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='firma_instructor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='nombre_enteconformador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
