# Generated by Django 4.2.7 on 2024-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0003_alter_evaluacion_firma_aprendiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='nombre_instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='nombre_instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones_aprendiz',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones_ente_conformador',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='tipo_informe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
