# Generated by Django 4.2.7 on 2023-11-04 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_jefe_inmediato', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('nivel_formacion', models.CharField(choices=[('Tecnico', 'Técnico'), ('Tecnologo', 'Tecnólogo')], max_length=50)),
                ('horario_formacion', models.CharField(choices=[('Mixta', 'Mixta'), ('Diurna', 'Diurna')], max_length=50)),
                ('cantidad_aprendices', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='InstructorEncargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAprendices.ficha')),
            ],
            options={
                'verbose_name': 'Instructor encargado',
                'verbose_name_plural': 'Instructores Encargados',
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_expedicion', models.DateField()),
                ('lugar_expedicion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('direccion_domicilio', models.TextField()),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('numero_celular1', models.CharField(max_length=20)),
                ('numero_celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_principal', models.EmailField(max_length=254)),
                ('correo_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('finalizacion_etapa_lectiva', models.DateField()),
                ('estado_aprobacion', models.CharField(choices=[('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado'), ('pendiente', 'Pendiente')], max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAprendices.empresa')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendiz', to='gestionAprendices.ficha', unique=True)),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
            },
        ),
    ]
