# Generated by Django 4.2.7 on 2024-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
