# Generated by Django 4.2.7 on 2024-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0002_empresa_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado_aprobacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=50),
        ),
    ]
