# Generated by Django 4.2.7 on 2024-03-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0003_alter_aprendiz_estado_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado_aprobacion',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('no_aprobado', 'No aprobado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=50),
        ),
    ]
