# Generated by Django 4.2.7 on 2023-11-14 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0004_alter_aprendiz_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('carta_laboral', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('certificado_agencia_publica', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pruebas_tyt', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('carnet_destruido', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('formato_bitacoras', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion_aprendiz', to='gestionAprendices.aprendiz')),
                ('instructor_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion_instructor', to='gestionAprendices.instructorencargado')),
            ],
        ),
    ]
