# Generated by Django 4.2.7 on 2024-05-24 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0006_documentos_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioFinalAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madre_cabeza_familia', models.BooleanField(default=False)),
                ('titulo_obtenido', models.CharField(max_length=100)),
                ('fecha_fin_etapa_lectiva', models.DateField()),
                ('cargo_funciones', models.CharField(max_length=100)),
                ('fecha_fin_etapa_productiva', models.DateField()),
                ('practica_aprendido', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('estudios_superiores_adicionales', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('estudios', models.CharField(blank=True, max_length=100, null=True)),
                ('trabaja_actualmente', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('estado_actual', models.CharField(choices=[('EMPLEADO', 'Empleado'), ('INDEPENDIENTE', 'Independiente')], max_length=20)),
                ('cargo_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_labora', models.CharField(blank=True, max_length=100, null=True)),
                ('antiguedad_trabajo', models.PositiveIntegerField(blank=True, null=True)),
                ('area_informacion_complementaria', models.CharField(max_length=100)),
                ('actualmente_estudia', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('estudia_que', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('certificar_competencias_laborales', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('conoce_beneficios_sena', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('idea_negocio', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('conoce_servicio_fondo_emprender', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('necesita_empleo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('sugerencias_comentarios', models.TextField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_final', to='gestionAprendices.aprendiz')),
            ],
        ),
    ]
