# Generated by Django 4.2.7 on 2024-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0007_formulariofinalaprendiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariofinalaprendiz',
            options={'verbose_name': 'Formulario final del aprendiz', 'verbose_name_plural': 'Formularios finales de los aprendices'},
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='actualmente_estudia',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='certificar_competencias_laborales',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='conoce_beneficios_sena',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='conoce_servicio_fondo_emprender',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='estudios_superiores_adicionales',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='idea_negocio',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='madre_cabeza_familia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='necesita_empleo',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='practica_aprendido',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='titulo_obtenido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='trabaja_actualmente',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
    ]
