# Generated by Django 4.2.7 on 2024-05-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0009_alter_formulariofinalaprendiz_practica_aprendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='estado_actual',
            field=models.CharField(max_length=20),
        ),
    ]
