# Generated by Django 4.2.7 on 2024-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0010_alter_formulariofinalaprendiz_estado_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariofinalaprendiz',
            name='practica_aprendido',
            field=models.CharField(max_length=50),
        ),
    ]
