# Generated by Django 4.2.7 on 2024-06-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0011_alter_formulariofinalaprendiz_practica_aprendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
    ]
