# Generated by Django 4.2.7 on 2024-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAprendices', '0013_alter_ficha_nivel_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado_aprobacion',
            field=models.CharField(blank=True, default='pendiente', max_length=50),
        ),
    ]
